# Generated by Django 2.1.1 on 2018-09-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_auto_20180923_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='rating_note',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
