# Generated by Django 2.1.1 on 2018-09-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_equipment', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristdestination',
            name='tourist_equipment',
            field=models.ManyToManyField(to='tourist_equipment.TouristEquipment'),
        ),
    ]
