# Generated by Django 2.1.1 on 2018-09-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('comments', '0001_initial'),
        ('core', '0002_touristdestination_tourist_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristdestination',
            name='assessments',
            field=models.ManyToManyField(to='assessments.Assessment'),
        ),
        migrations.AddField(
            model_name='touristdestination',
            name='comments',
            field=models.ManyToManyField(to='comments.Comment'),
        ),
    ]
