# Generated by Django 2.1.1 on 2018-09-23 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locality', '0002_auto_20180923_1607'),
        ('core', '0004_auto_20180923_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristdestination',
            name='locality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='locality.Locality'),
            preserve_default=False,
        ),
    ]
