# Generated by Django 2.1.1 on 2018-09-23 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_touristdestination_locality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristdestination',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locality.Locality'),
        ),
    ]
