# Generated by Django 2.1.1 on 2018-09-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180923_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristdestination',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tourist_destination'),
        ),
    ]
