# Generated by Django 2.1.1 on 2018-09-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locality',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
