# Generated by Django 2.1.1 on 2018-09-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locality', '0002_auto_20180923_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='locality',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='locality',
            name='line1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='locality',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
