# Generated by Django 2.1.1 on 2018-09-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locality', '0003_auto_20180924_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locality',
            name='country',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locality',
            name='line1',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locality',
            name='state',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
